package params

// ResourceType 资源类型
// 添加新资源类型请更新IsValid、init函数
type ResourceType string

// resource types
const (
	ResourceTypeBSN                              ResourceType = "bsn"
	ResourceTypeInstance                         ResourceType = "instance"
	ResourceTypeDisk                             ResourceType = "disk"
	ResourceTypeEIP                              ResourceType = "ip"
	ResourceTypeSnapshot                         ResourceType = "snapshot"
	ResourceTypeSnapshotPolicy                   ResourceType = "snapshot_policy"
	ResourceTypeSecurityGroup                    ResourceType = "security_group"
	ResourceTypeSecurityGroupRule                ResourceType = "security_group_rule"
	ResourceTypeVSwitch                          ResourceType = "vswitch"
	ResourceTypeVpc                              ResourceType = "vpc"
	ResourceTypeImage                            ResourceType = "image"
	ResourceTypeKeyPair                          ResourceType = "key_pair"
	ResourceTypeBandwidth                        ResourceType = "bandwidth"
	ResourceTypeLoadBalancer                     ResourceType = "load_balancer"
	ResourceTypeListener                         ResourceType = "listener"
	ResourceTypeMsGroup                          ResourceType = "ms_group"
	ResourceTypeBackend                          ResourceType = "backend"
	ResourceTypeVsGroup                          ResourceType = "vs_group"
	ResourceTypeSlbRule                          ResourceType = "slb_rule"
	ResourceTypeSlbAccess                        ResourceType = "slb_access"
	ResourceTypeSlbCert                          ResourceType = "slb_cert"
	ResourceTypeSlbACL                           ResourceType = "slb_acl"
	ResourceTypeRedis                            ResourceType = "redis"
	ResourceTypeRDSInstance                      ResourceType = "rds_instance"
	ResourceTypeRDSStorage                       ResourceType = "rds_storage"
	ResourceTypeRDSBackup                        ResourceType = "rds_backup"
	ResourceTypeRDSSql                           ResourceType = "rds_sql"
	ResourceTypeRDSMonitor                       ResourceType = "rds_monitor"
	ResourceTypeRDSNetwork                       ResourceType = "rds_network"
	ResourceTypeRDSDatabase                      ResourceType = "rds_database"
	ResourceTypeRDSDatabaseProxy                 ResourceType = "rds_database_proxy"
	ResourceTypeVRouter                          ResourceType = "v_router"
	ResourceTypeVRouteEntry                      ResourceType = "v_route_entry"
	ResourceTypeVRouterInterface                 ResourceType = "v_router_interface"
	ResourceTypeBGPIP                            ResourceType = "bgpip"
	ResourceTypeBGPIPBasic                       ResourceType = "security_bgpip_basic"   // 安全产品: 基础防御
	ResourceTypeBGPIPElastic                     ResourceType = "security_bgpip_elastic" // 安全产品: 弹性防护
	ResourceTypeBGPIPTrans                       ResourceType = "security_bgpip_trans"   // 安全产品: 转发流量
	ResourceTypeBGPIPCCStrategy                  ResourceType = "bgpip_cc_strategy"
	ResourceTypeBGPIPTransferLevel4              ResourceType = "bgpip_transfer_level_4"
	ResourceTypeBGPIPTransferLevel7              ResourceType = "bgpip_transfer_level_7"
	ResourceTypeBGPIPBlackList                   ResourceType = "bgpip_blacklist"
	ResourceTypeBGPIPWhiteList                   ResourceType = "bgpip_whitelist"
	ResourceTypeBGPIPWhiteBlackList              ResourceType = "bgpip_white_blacklist"
	ResourceTypeBGPIPCCPolicy                    ResourceType = "cc_policy"
	ResourceTypeBGPIPCCPolicyFrequencyRule       ResourceType = "cc_frequency_rule"
	ResourceTypeBGPIPCert                        ResourceType = "bgpip_cert"
	ResourceTypeVpnGateway                       ResourceType = "vpn_gateway"
	ResourceTypeCustomerVpnGateway               ResourceType = "customer_vpn_gateway"
	ResourceTypeIpsecConnection                  ResourceType = "ipsec_connection"
	ResourceTypeSslVpnServer                     ResourceType = "ssl_vpn_server"
	ResourceTypeSslVpnClient                     ResourceType = "ssl_vpn_client"
	ResourceTypeIpsecVpnGateway                  ResourceType = "ipsec_vpn_gateway"
	ResourceTypeSSLVpnGateway                    ResourceType = "ssl_vpn_gateway"
	ResourceTypeVpnGatewayBandwidth              ResourceType = "vpn_gateway_bandwidth"
	ResourceTypeSSLVpnGatewayConn                ResourceType = "ssl_vpn_gateway_conn"
	ResourceTypeNasAccessGroup                   ResourceType = "nas_access_group"
	ResourceTypeNasAccessRule                    ResourceType = "nas_access_rule"
	ResourceTypeNasFileSystem                    ResourceType = "nas_file_system"
	ResourceTypeMountTarget                      ResourceType = "nas_mount_target"
	ResourceTypeWAF                              ResourceType = "waf"
	ResourceTypeWAFBasic                         ResourceType = "security_waf_basic"
	ResourceTypeWAFDomain                        ResourceType = "waf_domain"
	ResourceTypeWAFPackagePool                   ResourceType = "waf_package_pool"
	ResourceTypeWAFAvoidTamper                   ResourceType = "waf_avoid_tamper"
	ResourceTypeWAFCCRule                        ResourceType = "waf_cc_rule"
	ResourceTypeWAFAvoidLeak                     ResourceType = "waf_avoid_leak"
	ResourceTypeWAFCustomizedRule                ResourceType = "waf_customized_rule"
	ResourceTypeWAFInstance                      ResourceType = "waf_instance"   // waf实例,涵盖[套餐]和[域名包]
	ResourceTypeMongoDBInstance                  ResourceType = "mongo_instance" // 仅仅供给meter,暂时存在,后续订单改在
	ResourceTypeMongoDBNode                      ResourceType = "mongo_node"     // mongo分片集群节点
	ResourceTypeMongoDBStorage                   ResourceType = "mongo_storage"  // 仅仅供给meter,暂时存在,后续订单改在
	ResourceTypeAutoRenew                        ResourceType = "auto_renew"
	ResourceTypeNATGateway                       ResourceType = "nat_gateway"
	ResourceTypeNATDNATTable                     ResourceType = "nat_dnat_table"
	ResourceTypeNATSNATTable                     ResourceType = "nat_snat_table"
	ResourceTypeNewBGPIP                         ResourceType = "new_bgpip"
	ResourceTypeNewBGPIPInstance                 ResourceType = "new_bgpip_instance"
	ResourceTypeNewBGPIPElastic                  ResourceType = "new_bgpip_elastic"
	ResourceTypeNewBGPIPLayer4Rule               ResourceType = "new_bgpip_layer4rule"
	ResourceTypeNewBGPIPLayer7Rule               ResourceType = "new_bgpip_layer7rule"
	ResourceTypeNewBGPIPBlackWhiteList           ResourceType = "new_bgpip_blackwhitelist"
	ResourceTypeNewBGPIPLayer7CCRule             ResourceType = "new_bgpip_layer7ccrule"
	ResourceTypeScalingGroup                     ResourceType = "scaling_group"
	ResourceTypeScalingActivity                  ResourceType = "scaling_activity"
	ResourceTypeScalingConfiguration             ResourceType = "scaling_configuration"
	ResourceTypeScalingNotificationConfiguration ResourceType = "scaling_notification_configuration"
	ResourceTypeScalingRule                      ResourceType = "scaling_rule"
	ResourceTypeScalingScheculedTask             ResourceType = "scaling_scheduled_task"
	ResourceTypeScalingLifecycleHook             ResourceType = "scaling_lifecycle_hook"
	ResourceTypeMqInstance                       ResourceType = "mq_instance"
	ResourceTypeMqTopic                          ResourceType = "mq_topic"
	ResourceTypeCommonBandwidth                  ResourceType = "common_bandwidth"
	ResourceTypeCenBandwidth                     ResourceType = "cen_bandwidth"
	ResourceTypePolarDB                          ResourceType = "polardb"          // 云数据库polarDB
	ResourceTypePolarDBStorage                   ResourceType = "polardb_storage"  // 云数据库polarDB存储包
	ResourceTypePolarDBDatabase                  ResourceType = "polardb_database" // polardb database
	ResourceTypePolarDBNode                      ResourceType = "polardb_node"     // polardb 节点
	ResourceTypePolarDBAccount                   ResourceType = "polardb_account"  // polardb 账号
	ResourceTypePolarDBBackup                    ResourceType = "polardb_backup"   // polardb 备份
	ResourceTypePolarDBNetwork                   ResourceType = "polardb_network"  // polardb 网络连接
	ResourceTypeIPv6Gateway                      ResourceType = "ipv6_gateway"
	ResourceTypeIPv6EgressOnlyRule               ResourceType = "ipv6_egress_only_rule"
	ResourceTypeIPv6Address                      ResourceType = "ipv6_address"
	ResourceTypeIPv6AddressBandwidth             ResourceType = "ipv6_address_bandwidth"
)
